language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

before_deploy:
  - yarn build
    
deploy:
  - provider: script
    script: now alias $(now ./build --public --token $NOW_TOKEN) $DEV_URL --token $NOW_TOKEN
    skip_cleanup: true
    on:
      branch: develop
      
  - provider: script
    script: now alias $(now ./build --public --token $NOW_TOKEN) $PROD_URL --token $NOW_TOKEN
    skip_cleanup: true
    on:
      branch: master